"""KnowledgeBackend protocol — pluggable storage for knowledge."""

from __future__ import annotations

from typing import Protocol

from ganglion.knowledge.types import Antipattern, KnowledgeQuery, Pattern


class KnowledgeBackend(Protocol):
    """Protocol for knowledge store backends."""

    def save_pattern(self, pattern: Pattern) -> None: ...
    def save_antipattern(self, antipattern: Antipattern) -> None: ...
    def query_patterns(self, query: KnowledgeQuery) -> list[Pattern]: ...
    def query_antipatterns(self, query: KnowledgeQuery) -> list[Antipattern]: ...
    def count(self) -> dict[str, int]: ...
    def trim(self, max_patterns: int = 500, max_antipatterns: int = 500) -> None: ...
